name: docker

on:
    push:
        tags:
            - 'v*'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install bazelisk
              run: |
                  curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
                  mkdir -p "${GITHUB_WORKSPACE}/bin/"
                  mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
                  chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      ${{github.repository}}
                  tags: |
                      type=semver,pattern={{major}}.{{minor}}.{{patch}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - run: |
                  bazel build //src:image.tar 
                  docker load -i bazel-bin/src/image.tar
              name: Build base image with Bazel
            - name: Push
              run: |
                  for tag in $(jq -r '.tags[]' <<< "$DOCKER_METADATA_OUTPUT_JSON"); do
                    echo "pushing $tag"
                    docker tag bazel/src:image $tag
                    docker push $tag
                  done
